// PHARR WAY QUESTION BANK
// - "Pharr Way" questions are tagged as "Workforce" so they share that board column.
// - "Results" category has been removed entirely.
// Fields: id, cat, diff (E/M/H), q, a, src
const PHARR_QUESTIONS = [
  {id:1,cat:"Workforce",diff:"E",q:"What are the three pillars of the Pharr Way?",a:"People, Process, and Performance.",src:"Best Practices — The Pharr Way"},
  {id:2,cat:"Workforce",diff:"E",q:'Pharr\'s mission is: "To provide the _______ level of municipal services every day."',a:"Highest.",src:"Organizational Profile"},
  {id:3,cat:"Workforce",diff:"E",q:"What is Pharr's vision statement?",a:'"To consistently lead the region in municipal excellence, sustainability, and innovation."',src:"Organizational Profile"},
  {id:4,cat:"Workforce",diff:"E",q:"What are Pharr's core values called, and what letter do they spell?",a:"PRIDE values.",src:"Leadership Process — LP 1.1"},
  {id:5,cat:"Workforce",diff:"M",q:"What does ATP stand for, and what does it connect?",a:"Align Team Pharr. ATP connects leadership, strategic planning, budgeting, workforce planning, operations, performance management, and continuous improvement into one integrated framework.",src:"Best Practices — ATP"},
  {id:6,cat:"Workforce",diff:"E",q:"True or False: The Pharr Way is a cultural framework that connects daily work to the City's mission.",a:"True.",src:"Best Practices — The Pharr Way"},
  {id:7,cat:"Workforce",diff:"M",q:"How many active community partnerships has Pharr grown to? A) 17  B) 27  C) 37  D) 47",a:"C) 37.",src:"Leadership Process — LP 6.1"},
  {id:8,cat:"Workforce",diff:"M",q:'What does "Excellence Every Day" mean in practice for a frontline employee?',a:"Every employee, in every interaction, delivers the highest level of service regardless of role.",src:"Organizational Profile"},
  {id:9,cat:"Workforce",diff:"H",q:"What does the Process pillar of the Pharr Way say about how exceptional service gets delivered?",a:"Exceptional service depends on consistent, collaborative, and continuously improved work systems.",src:"Best Practices — The Pharr Way"},
  {id:10,cat:"Workforce",diff:"M",q:"True or False: The Pharr Way was created by leadership and handed down to employees.",a:"False. It was built by the people who use it every day for the residents they serve.",src:"Best Practices — ATP"},
  {id:11,cat:"Leadership",diff:"E",q:"The Leadership System deploys the MVV through a ____-step repeatable process.",a:"5-step process: Establish direction, translate MVV, align resources through ABP, deploy through the employee lifecycle, evaluate and improve.",src:"Leadership Process — LP 1.1"},
  {id:12,cat:"Leadership",diff:"E",q:"How often do Strategic Alignment Meetings (SAMs) take place? A) Weekly  B) Monthly  C) Bi-monthly  D) Quarterly",a:"C) Bi-monthly.",src:"Leadership Process — LP 2.1"},
  {id:13,cat:"Leadership",diff:"M",q:"What happened after the 2020 AES showed only 84% of employees understood the MVV?",a:"OSE launched a citywide campaign using visual aids, communication tools, and leadership reinforcement — producing a 16-percentage-point increase in the next AES.",src:"Leadership Process — LP 1.1"},
  {id:14,cat:"Leadership",diff:"E",q:"True or False: The Board of Commissioners approves Pharr's Mission, Vision, and Values.",a:"True.",src:"Leadership Process — LP 1.1"},
  {id:15,cat:"Leadership",diff:"M",q:"What percentage of City Management and Senior Leader positions have been filled through internal succession?",a:"70%.",src:"Leadership Process — LP 4.1"},
  {id:16,cat:"Leadership",diff:"M",q:"The Pathway to Leadership program has developed _____ employees across _____ cohorts.",a:"228 employees across eight cohorts.",src:"Leadership Process — LP 4.2"},
  {id:17,cat:"Leadership",diff:"E",q:"What does Trackstar do at the City of Pharr?",a:"Trackstar is the City's employee evaluation platform — strengthening performance management, coaching, and goal alignment.",src:"Leadership Process — LP 3.1"},
  {id:18,cat:"Leadership",diff:"M",q:"True or False: Pharr established an Office of Professional and Ethical Standards in 2023.",a:"True.",src:"Leadership Process — LP 5.3"},
  {id:19,cat:"Strategy",diff:"E",q:"How many steps are in Pharr's Strategic Planning Process (SPP)?",a:"7 steps.",src:"Strategy Process — SP 1.1"},
  {id:20,cat:"Strategy",diff:"E",q:"What are Pharr's six Strategic Objectives?",a:"1) Service Excellence  2) Infrastructure  3) Quality of Life  4) Economic Vitality  5) Sound Governance and Fiscal Sustainability  6) Safe and Secure Community.",src:"Strategy Process — SP 1.1"},
  {id:21,cat:"Strategy",diff:"M",q:"What new elements were added to the Strategic Planning Process in FY 2024–2025, and why?",a:"SMART and SWOT Days — added after leadership identified a need for greater workforce participation in planning.",src:"Strategy Process — SP 1.1"},
  {id:22,cat:"Strategy",diff:"E",q:"Departments submit KPI updates to OSE by the ______ of each month.",a:"15th of each month.",src:"Strategy Process — SP 3.1"},
  {id:23,cat:"Strategy",diff:"E",q:"What does OSE issue monthly that recognizes achievements and flags improvement areas?",a:"Strengths and Opportunities (S&O) Reports.",src:"Strategy Process — SP 3.1"},
  {id:24,cat:"Strategy",diff:"H",q:"True or False: Pharr treats innovation as a separate activity outside the Strategic Planning Process.",a:"False. Innovation is embedded into the SPP — not a separate silo.",src:"Strategy Process — SP 4.1"},
  {id:25,cat:"Strategy",diff:"M",q:"What four criteria does Pharr use to evaluate whether an innovation opportunity should be pursued?",a:"1) Evidence of Impact  2) Strategic Alignment  3) Feasibility  4) Scalability and Sustainability.",src:"OI Process — OIP 3.1"},
  {id:26,cat:"Customers",diff:"E",q:"How many service types does the Pharr 311 system cover? A) 40  B) 70  C) 100  D) 311",a:"B) 70 service types.",src:"Customer Process — CP 4.1"},
  {id:27,cat:"Customers",diff:"E",q:"What was Pharr's Bi-Annual Citizen Survey satisfaction rate in FY 2026?",a:"94% — surpassing the USA Top Decile ETC benchmark of 89%.",src:"Customer Results"},
  {id:28,cat:"Customers",diff:"E",q:"True or False: The City of Pharr treats rising complaint volume as a sign of service failure.",a:"False. Pharr treats it as valuable intelligence to act upon.",src:"Customer Results"},
  {id:29,cat:"Customers",diff:"M",q:"What six steps make up Pharr's Customer Engagement and Relationship Management Process?",a:"Connect → Understand → Engage → Deliver → Measure → Improve.",src:"Customer Process — CP 2.1"},
  {id:30,cat:"Customers",diff:"E",q:"The Pharr 311 Mobile App was launched in _______ and is now a primary platform for service requests.",a:"2019.",src:"Customer Process — CP 1.1"},
  {id:31,cat:"Customers",diff:"M",q:"In how many languages does Pharr offer translation services? A) 12  B) 25  C) 50  D) More than 78",a:"D) More than 78 languages.",src:"Customer Process — CP 3.1"},
  {id:32,cat:"Customers",diff:"M",q:"What is Pharr's long-term residency rate, and why does it matter?",a:"58% long-term residency rate — a key indicator of customer loyalty in municipal government.",src:"Customer Process — CP 2.1"},
  {id:33,cat:"OI & STEP",diff:"E",q:"What does STEP stand for?",a:"Study, Track, Evaluate, Propose.",src:"Best Practices — STEP"},
  {id:34,cat:"OI & STEP",diff:"E",q:"STEP is deployed across all _____ City departments.",a:"27 departments.",src:"OI Process — OIP 2.1"},
  {id:35,cat:"OI & STEP",diff:"M",q:"What improvement methodology did OSE try before STEP, and why was it changed?",a:"PDSA. Employees needed a simpler, more practical methodology — so OSE adapted it into STEP.",src:"OI Process — OIP 2.1"},
  {id:36,cat:"OI & STEP",diff:"M",q:"How many STEP submissions has Pharr received since inception? A) 47  B) 72  C) 102  D) 228",a:"C) 102 submissions, with 47 adopted citywide.",src:"Best Practices — STEP"},
  {id:37,cat:"OI & STEP",diff:"M",q:"How much did a Finance STEP reduce P-Card processing time?",a:"From more than 6 business days to 2 days — a 67% reduction.",src:"Best Practices — STEP"},
  {id:38,cat:"OI & STEP",diff:"E",q:"What four statuses can OSE assign to a STEP submission?",a:"In-Progress, On-Hold, Adopted, or Not Adopted.",src:"OI Process — OIP 3.1"},
  {id:39,cat:"OI & STEP",diff:"H",q:"What is the annual savings from the Bridge Department's paperless leave request STEP?",a:"Approximately $4,898 annually.",src:"Best Practices — STEP"},
  {id:40,cat:"OI & STEP",diff:"H",q:"What results did Public Utilities achieve through a STEP on vehicle inspections?",a:"83% inspection compliance, 13% increase in vehicles inspected, 15% increase in employee submittal rates.",src:"Best Practices — STEP"},
  {id:41,cat:"Workforce",diff:"E",q:"What survey does Pharr administer annually to measure employee satisfaction and culture?",a:"The Annual Employee Survey (AES).",src:"Workforce Results — WR 1.1"},
  {id:42,cat:"Workforce",diff:"E",q:"What was Pharr's overall employee satisfaction rate in FY 2025? A) 87%  B) 91%  C) 95%  D) 99%",a:"C) 95%.",src:"Workforce Results — WR 2.1"},
  {id:43,cat:"Workforce",diff:"M",q:"True or False: 100% of Pharr employees receive a formal performance review at least annually.",a:"True.",src:"Workforce Results — WR 3.2"},
  {id:44,cat:"Workforce",diff:"M",q:"What is Pharr's 90-day new hire turnover rate in FY 2025?",a:"0.95% — below the HRBench Top Quartile of 1.73%.",src:"Workforce Results — WR 4.1"},
  {id:45,cat:"Workforce",diff:"M",q:"Pharr invests $_____ per FTE in training annually — nearly double the SHRM Top Quartile benchmark of $_____.",a:"$937 per FTE vs. SHRM Top Quartile of $500.",src:"Workforce Results — WR 6.1"},
  {id:46,cat:"Workforce",diff:"E",q:"How many training days per employee did Pharr record in FY 2025?",a:"8.25 training days per FTE.",src:"Workforce Results — WR 6.2"},
  {id:47,cat:"Workforce",diff:"H",q:"What are the three stages of Pharr's Workforce Engagement System?",a:"Stage 1: Recruit and Onboard. Stage 2: Engage, Recognize, and Develop. Stage 3: Evaluate and Improve.",src:"Workforce Process — WP 1.1"},
  {id:48,cat:"Workforce",diff:"M",q:"What is Pharr's employee absenteeism rate compared to the APQC benchmark?",a:"1.0–1.1 days average — far below the APQC benchmark of approximately 6.0 days.",src:"Workforce Results — WR 3.4"},
  {id:49,cat:"Operations",diff:"E",q:"What platform does Pharr use to qualify and select vendors? A) SharePoint  B) Procureware  C) Trackstar  D) 311",a:"B) Procureware.",src:"Operations Process — OP 4.1"},
  {id:50,cat:"Operations",diff:"M",q:"True or False: Pharr is subject to mandatory OSHA regulation as a municipality.",a:"False. Pharr voluntarily adheres to OSHA guidelines as a best practice.",src:"Operations Results — OR 5.3"},
  {id:51,cat:"Operations",diff:"H",q:"What three primary defense vectors does Pharr use to manage cybersecurity?",a:"People, Technology, and Policies and Procedures — organized under the NIST Cybersecurity Framework.",src:"Operations Process — OP 6.1"},
  {id:52,cat:"Operations",diff:"E",q:"The five-step Customer Requirements Determination Process identifies, ________, prioritizes, and integrates customer requirements into service delivery.",a:"Analyzes.",src:"Operations Process — OP 1.1"},
];